### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './HeadCube3D/images/300W_LP/AFW_1051618982_1_0_flip.jpg'

### ISSUE THREAD

**Issue by Algabri** [hnuzhy/DirectMHP#1]
Could you provide the code to generate train_300W_LP.json, val_AFLW2000.json and BIWI_test.json because the names of images are different?
It will be really helpful.

**Comment by hnuzhy** [comment]
> Could you provide the code to generate train_300W_LP.json, val_AFLW2000.json and BIWI_test.json because the names of images are different? It will be really helpful.

I will upload the corresponding images as writen in https://github.com/hnuzhy/DirectMHP/blob/main/README.md#single-hpe-datasets `The corresponding resorted images used in our DirectMHP can be downloaded 300W-LP.zip, AFLW2000.zip and BIWI_test.zip.` Please wait for some time.
