### ISSUE TITLE
NameError: Error: not a valid dataset name

### ISSUE THREAD

**Issue by Algabri** [hnuzhy/DirectMHP#11]
Hi, Hnuzhy
When I try to run :
`python train.py --lr 0.0001 --dataset AGORA --data_dir datasets/AGORA/train   --filename_list datasets/AGORA/files_train.txt --num_epochs 100 --batch_size 256 --gpu 0`

I got this error:

```
 Traceback (most recent call last):
  File "train.py", line 133, in <module>
    pose_dataset = datasets.getDataset(
  File "/home/redhwan/2/HPE/6DRepNet/sixdrepnet/datasets.py", line 323, in getDataset
    raise NameError('Error: not a valid dataset name')
NameError: Error: not a valid dataset name
```
When I checked the [code](https://github.com/thohemp/6DRepNet/blob/master/sixdrepnet/datasets.py), I found no class for **AGORA** and **CMU** datasets.
 
Could you provide your code for that, please?

**Comment by hnuzhy** [comment]
OK. Some code of **6DRepNet** does need to be changed for the full-range single HPE training. I have uploaded my revised version in `./exps/sixdrepnet.zip`. You can refer it for your reproducing.

**Comment by Algabri** [comment]
Thank you so much for your help and quick answer.
