### ISSUE TITLE
关于构建AGORA-HPE数据集

### ISSUE THREAD

**Issue by wangzixing1998** [hnuzhy/DirectMHP#15]
![image](https://user-images.githubusercontent.com/56664933/234009513-a021501f-aea2-44a2-9fd2-0d4b08cbe9a6.png)
step2步骤中声明 需要从官方网站中获得npz版本的SMPL-X模型，并将其命名为SMPLX_MALE.npz, SMPLX_FEMALE.npz 和 SMPLX_NEUTRAL.npz。但是官方网站中，npz版本的模型只有neutral SMPL-X 。
![image](https://user-images.githubusercontent.com/56664933/234010506-c5404741-5895-44a3-aa9d-52019250cf3a.png)
能够详细说明下如何从官方网站中获得SMPLX_MALE.npz, SMPLX_FEMALE.npz 和 SMPLX_NEUTRAL.npz这三个模型吗

**Comment by hnuzhy** [comment]
It has been a long time, and the website may have been updated. Maybe you can find three SMPL-X `.npz` model files by downloading `SMPL-X V1.1` as shown below.

![image](https://user-images.githubusercontent.com/21312423/234036977-66958481-824f-4352-8cc4-241f0561222d.png)

The renaming operation is following formats in this link https://github.com/vchoutas/smplx/tree/main#model-loading
