### ISSUE TITLE
About application method.

### ISSUE THREAD

**Issue by Mt-Taka0129** [hnuzhy/DirectMHP#17]
Hello. I have one question about the application method.
Is it possible to add an object tracking feature to this program?
If that is possible, please let me know if there is any way to do this.

**Comment by hnuzhy** [comment]
Do you mean head detection + head pose estiamtion + head tracking? While, I do not think that we can make it in an end-to-end way. As far as I known, object tracking currently follows a two-stage setting: detection and tracking. You may add head tracking function based on results by DirectMHP. For example, a post-processing offline-tracking operation on detected head bboxes. You can achieve this by referring YOLOV5+DeepSORT. I remember that is can be searched in github.

**Comment by Mt-Taka0129** [comment]
Thanks for the reply !
If I can track offline based on DirectMHP results, it will meet my requirements.
I will look into YOLOV5+DeepSORT.

**Comment by Mt-Taka0129** [comment]
Sorry, I have another question about `demos/image.py`.

```
def plot_3axis_Zaxis(img, yaw, pitch, roll, tdx=None, tdy=None, size=50., limited=True, thickness=2):
    # Input is a cv2 image
    # pose_params: (pitch, yaw, roll, tdx, tdy)
    # Where (tdx, tdy) is the translation of the face.
    # For pose we have [pitch yaw roll tdx tdy tdz scale_factor]

    p = pitch * np.pi / 180
    y = -(yaw * np.pi / 180)
    r = roll * np.pi / 180
```
When drawing the three axes, why is only the Yaw angle multiplied by a minus sign?

Also, is the head posture, the output of the neural network, an Eulerian angular representation (z-x-y system) with the camera coordinate system (image below) rotated in the order of Z-axis, Y-axis and X-axis?
![無題](https://github.com/hnuzhy/DirectMHP/assets/85815821/d32a1fdf-9828-4397-b009-84ee6304618d)
