### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by wangzixing1998** [hnuzhy/DirectMHP#18]
您好，使用agora数据集进行训练后，得到了narrow-range和full-range两个测试的结果
![image](https://github.com/hnuzhy/DirectMHP/assets/56664933/a00f8c50-0a9c-4b11-a22c-6a188db9282c)
请问，这两个测试结果都是使用下面的损失函数训练的模型吗
![image](https://github.com/hnuzhy/DirectMHP/assets/56664933/a8266693-7d50-40f8-ad2a-75feafa7a1bf)

**Comment by wangzixing1998** [comment]
![image](https://github.com/hnuzhy/DirectMHP/assets/56664933/d634d727-294a-4b6e-85f0-e1f1a52c224c)
我阅读了代码，训练时这个self.wrapped为ture吗

**Comment by hnuzhy** [comment]
self.wrapped默认为Flase。paper里面的分解实验已经说明了，使用wrapped loss这个设置有害无益，这个loss最开始是WHE-Net提出来的，用来针对全向单人头姿态估计任务
