### ISSUE TITLE
模型test的问题

### ISSUE THREAD

**Issue by wangzixing1998** [hnuzhy/DirectMHP#19]
你好在加载[agora_s_1280_e300_t40_lw010_best.pt]模型参数到网络中时出现了以下问题。
![image](https://github.com/hnuzhy/DirectMHP/assets/56664933/f145e936-98ca-4a96-b7d9-1298a4451b01)

**Comment by hnuzhy** [comment]
It seems that you may have downloaded a broken model weight file, Please re-download it fully.
https://github.com/WongKinYiu/yolor/issues/269
https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key

**Comment by wangzixing1998** [comment]
您好，这个[WongKinYiu/yolor/issues/269](https://github.com/WongKinYiu/yolor/issues/269)链接用于下载yolo预训练模型，并非是我需要的模型。我想要直接测试在AGORA-HPE上训练完成的模型。之前的模型的下载来源如下：
![image](https://github.com/hnuzhy/DirectMHP/assets/56664933/4a2ce3ca-67dc-4c66-ba26-d9b5c9366dca)

**Comment by hnuzhy** [comment]
我的意思是，你这个bug和给出的两个链接中的问题类似。你需要重新下载权重文件，之前下载的有可能是损坏的

**Comment by wangzixing1998** [comment]
我是今天下午下载的

**Comment by hnuzhy** [comment]
我又更新了一下权重文件，你再下载试一下是否能用。如果还是不行，再查一下是否是python环境的问题

**Comment by wangzixing1998** [comment]
没问题了
