### ISSUE TITLE
RuntimeError: size of dimension does not match previous size, operand 1, dim 2

### ISSUE THREAD

**Issue by Algabri** [hnuzhy/DirectMHP#2]
I got this error:
```
$ project_joints --imgFolder demo/images/train --loadPrecomputed demo/Cam/train_Cam   --modeltype SMPLX --kid_template_path utils/smplx_kid_template.npy --modelFolder demo/model   --gt_model_path demo/GT_fits/ --imgWidth 1280 --imgHeight 720
DEBUG:matplotlib:matplotlib data path: /home/redhwan/.local/lib/python3.8/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/redhwan/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/redhwan/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/redhwan/.cache/matplotlib/fontlist-v330.json
0it [00:00, ?it/s]INFO:root:Processing 0th dataframe
INFO:root:Generating Ground truth joints
  0%|▏                                                                                        | 4/1453 [00:01<11:08,  2.17it/s]
0it [00:05, ?it/s]                                                                            | 4/1453 [00:01<09:02,  2.67it/s]
Traceback (most recent call last):
  File "/home/redhwan/.local/bin/project_joints", line 8, in <module>
    sys.exit(project_joints())
  File "/home/redhwan/.local/lib/python3.8/site-packages/agora_evaluation/cli.py", line 26, in project_joints
    run_projection(sys.argv[1:])
  File "/home/redhwan/.local/lib/python3.8/site-packages/agora_evaluation/project_joints.py", line 77, in run_projection
    df = add_joints_verts_in_dataframe(args, df, store_joints)
  File "/home/redhwan/.local/lib/python3.8/site-packages/agora_evaluation/get_joints_verts_from_dataframe.py", line 240, in add_joints_verts_in_dataframe
    gt_verts_cam_2d, gt_verts_cam_3d, gt_joints_cam_2d, gt_joints_cam_3d = get_projected_joints(args, df,
  File "/home/redhwan/.local/lib/python3.8/site-packages/agora_evaluation/get_joints_verts_from_dataframe.py", line 209, in get_projected_joints
    gt_joints_local, gt_verts_local = get_smplx_vertices(args.numBetas, kid_flag, gt, gender,
  File "/home/redhwan/.local/lib/python3.8/site-packages/agora_evaluation/get_joints_verts_from_dataframe.py", line 105, in get_smplx_vertices
    smplx_gt = model_gt(
  File "/home/redhwan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/redhwan/.local/lib/python3.8/site-packages/smplx/body_models.py", line 1242, in forward
    vertices, joints = lbs(shape_components, full_pose, self.v_template,
  File "/home/redhwan/.local/lib/python3.8/site-packages/smplx/lbs.py", line 209, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/home/redhwan/.local/lib/python3.8/site-packages/smplx/lbs.py", line 295, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/redhwan/.local/lib/python3.8/site-packages/torch/functional.py", line 241, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2

```

Note: it was working fine with validation data.
How we can solve this issue?

My system is:
Python 3.8 
ubuntu 20.04

**Comment by hnuzhy** [comment]
I guess you may combine all the subtrain-set images into one folder for running this script.

**Comment by hnuzhy** [comment]
I guess you may combine all the subtrain-set images into one folder for running this script.

**Comment by hnuzhy** [comment]
I guess you may combine all the subtrain-set images into one folder for running this script.

**Comment by Algabri** [comment]
I have just combined them into one folder, as you suggested. Unfortunately, the same issue.

**Comment by hnuzhy** [comment]
> I have just combined them into one folder, as you suggested. Unfortunately, the same issue.

It is strange that the scripts are suitable for the val-set but not for the train-set. You may check and compare those related scripts to fix bugs.

**Comment by Algabri** [comment]
I have just tried to run train images with validation_Cam. it is working but when I used **train_Cam** is not working. It also is strange for me.

**Comment by Algabri** [comment]
If I download train_SMPLX.zip (25 GB), will I obtain the same results?

**Comment by hnuzhy** [comment]
> If I download train_SMPLX.zip (25 GB), will I obtain the same results?

The steps for generating AGORA-HPE do not include the `train_SMPLX.zip` file. You should not download it. For the generation of train-set, you may try not merge all ten `train_<id>` sub-folders into one `train` folder, and run the generation script again. I may give a wrong instruction cause having passed a long time.

**Comment by Algabri** [comment]
I tried one by one. The issue is in **train_Cam**. I will try until tomorrow to fix this issue.

**Comment by Algabri** [comment]
I have just solved this issue as:

I uninstalled smplx then re-installed again as I explain [here](https://github.com/vchoutas/smplify-x/issues/153#issuecomment-1430700430).

But, when I ran the $ `python data_process_hpe.py`, I found the code was not generating the `camera parameters`. The reason  was that you install  


```
$ cd /path/to/dataset/AGORA/agora_evaluation
$ pip install .
```

before replacing step for `projection.py` and `get_joints_verts_from_dataframe.py`

Now I am running the script `python data_process_hpe.py`. I faced a new issue. So, I will open new one.

**Comment by hnuzhy** [comment]
> I have just solved this issue as:
> 
> I uninstalled smplx then re-installed again as I explain [here](https://github.com/vchoutas/smplify-x/issues/153#issuecomment-1430700430).
> 
> But, when I ran the $ `python data_process_hpe.py`, I found the code was not generating the `camera parameters`. The reason was that you install
> 
> ```
> $ cd /path/to/dataset/AGORA/agora_evaluation
> $ pip install .
> ```
> 
> before replacing step for `projection.py` and `get_joints_verts_from_dataframe.py`
> 
> Now I am running the script `python data_process_hpe.py`. I faced a new issue. So, I will open new one.

That's great that you have fixed this bug :-)
