### ISSUE TITLE
About dataset prepare 

### ISSUE THREAD

**Issue by ly0018-yang** [hnuzhy/DirectMHP#20]
hello,I have a question about prepareing yolov5_labels in Single HPE datasets.
Could you please tell me how do I get yolov5_labels?

**Comment by ly0018-yang** [comment]
hello,I have a question about prepareing yolov5_labels in Single HPE datasets.
Could you please tell me how do I get yolov5_labels?

**Comment by hnuzhy** [comment]
I have already uploaded the processed images and labels in Hugging Face
https://huggingface.co/HoyerChou/DirectMHP#single-hpe-datasets-with-yolov5coco-format
If you want to generate labels in yolov5 style by yourself, please refer steps below:
https://github.com/hnuzhy/DirectMHP#single-hpe-datasets

**Comment by ly0018-yang** [comment]
Thanks for your answer! I know what to do.
