### ISSUE TITLE
Fig. 4. Pose label distribution of three Euler angles in datasets  300W-LP&AFLW2000 and BIWI.

### ISSUE THREAD

**Issue by Redhwan-A** [hnuzhy/DirectMHP#21]
Hello, Hnuzhy,

First of all, thank you so much for your sharing your work here.

It is amazing.

I already read your paper and implemented your code as you guided us in your [README.md](https://github.com/hnuzhy/DirectMHP#readme).

I did not find the code for Pose label distribution of three Euler angles in datasets  300W-LP&AFLW2000 and BIWI.
Could you share it here, please?

Thank you in advance!

**Comment by hnuzhy** [comment]
Do you mean the hist plot script of Fig.4? It is included in the processing code of datasets AGORA-HPE and CMU-HPE. I have already uploaded it in this repo. Please refer [AGORA-HPE hist plot](https://github.com/hnuzhy/DirectMHP/blob/main/exps/AGORA/data_process_hpe.py#L428) and [CMU-HPE hist plot](https://github.com/hnuzhy/DirectMHP/blob/main/exps/CMU/data_split_hpe.py#LL165C40-L165C40)

**Comment by Redhwan-A** [comment]
The [AGORA-HPE hist plot](https://github.com/hnuzhy/DirectMHP/blob/main/exps/AGORA/data_process_hpe.py#L428) and [CMU-HPE hist plot](https://github.com/hnuzhy/DirectMHP/blob/main/exps/CMU/data_split_hpe.py#LL165C40-L165C40), I already plot them.
I would like to plot datasets 300W-LP&AFLW2000 and BIWI as you did in Fig 4.

**Comment by hnuzhy** [comment]
OK! I have uploaded the corresponding script in [statistic_angles.py](https://github.com/hnuzhy/DirectMHP/blob/main/exps/statistic_angles.py). The original datasets 300W-LP&AFLW2000 and BIWI can be downloaded from the official repo of FSA-Net. Hoping this is helpful.

**Comment by Redhwan-A** [comment]
Thank you so much for your help.
