### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/AGORA/HPE/images/validation/2000100001.jpg'

### ISSUE THREAD

**Issue by ly0018-yang** [hnuzhy/DirectMHP#22]
hi, I first run the script data_process_hpe.py to generate coco_style_train.json file and coco_style_validation.json file, I had
set dubug = False and has_parsed = False. But I got a error: FileNotFoundError: [Errno 2] No such file or directory: './datasets/AGORA/HPE/images/validation/2000100001.jpg' . How can I solve this problem? Thank you in advance for your help.

**Comment by hnuzhy** [comment]
It seems like a problem of wrong file paths. Please check your path `./datasets/AGORA/HPE/images/` carefully if it is missed, wrong or unreachable.

**Comment by ly0018-yang** [comment]
thanks for your answer！
