### ISSUE TITLE
 构建AGORA-HPE数据集

### ISSUE THREAD

**Issue by ly0018-yang** [hnuzhy/DirectMHP#24]
你好，我在生成AGORA_HPE第四步（得到train和coco_style_train.json）时，遇到以下问题：
![111](https://github.com/hnuzhy/DirectMHP/assets/61495072/9a8e84e8-0420-4862-8aa6-c93826d66ea1)
然后发现`list(data.keys())`中没有`['cam_j3d']`、`['camR']`、`['camT']`、`['camK']`：
![222](https://github.com/hnuzhy/DirectMHP/assets/61495072/e182d3ab-791b-4541-a01c-94d7edbd38bc)
![333](https://github.com/hnuzhy/DirectMHP/assets/61495072/e77f6270-5818-4e46-aebf-36c382090242)
请问这种情况有遇到吗？该如何解决呢？

**Comment by JamesL404** [comment]
你好请问你怎么解决的呢？我也遇到了一样的问题
