### ISSUE TITLE
test.py for sixdrepnet

### ISSUE THREAD

**Issue by KimNaser** [hnuzhy/DirectMHP#27]
I read your paper, then I implemented the whole of your code.
It is more than amazing.

But I faced one issue.

When I tested the sixdrepnet code. Your test.py code is modified a little bit to be fit for full range angles compared to the [original code](https://github.com/thohemp/6DRepNet).

I used the [Fine-tuned models](https://drive.google.com/drive/folders/1V1pCV0BEW3mD-B9MogGrz_P91UhTtuE_) for the original work. your code gives the same result when batch_size = 1  `Yaw: 3.6289, Pitch: 4.9066, Roll: 3.3740, MAE: 3.9698`
 and gives a different result when batch_size = 64 `Yaw: 2.0235, Pitch: 1.1259, Roll: 2.1734, MAE: 1.7742`

Please, check your code and update it.

**Comment by hnuzhy** [comment]
Wow! It is really amazing that the MAE results became such better when the batch_size is adjusted to a large one. Actually, the work 6DRepNet gives a strong SOTA in single HPE task, especially for heads with visiable faces. This is an undoubtable fact. What I want to do is solving the full-range head. Maybe some changes happened when the batch_size not equals to 1. I'm not that sure. I'm now busy on other things, and will look into it later. Anyway, thank you for your report of this interesting finding.

**Comment by KimNaser** [comment]
Note,  when I change the batch_size (1, 64, 320, and 640) using the original code, it gives the same result but your code gives a different result at every batch_size. 
Thanks for your reply.
