### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './HPE/annotations/coco_style_validation.json'

### ISSUE THREAD

**Issue by Algabri** [hnuzhy/DirectMHP#3]
hi
Step 4 [here](https://github.com/hnuzhy/DirectMHP#agora-hpe-dataset), I am running the code `$ python data_process_hpe.py` to generate (coco_style_train.json / coco_style_validation.json).
I think that you forget the function to get them. 

Thank you in advance for your help.

**Comment by hnuzhy** [comment]
> hi Step 4 [here](https://github.com/hnuzhy/DirectMHP#agora-hpe-dataset), I am running the code `$ python data_process_hpe.py` to generate (coco_style_train.json / coco_style_validation.json). I think that you forget the function to get them.
> 
> Thank you in advance for your help.

You should set `debug = False` and  `has_parsed = False`  when you first run this script `data_process_hpe.py` for not having the `coco_style_validation.json` file or `coco_style_train.json`  file in your machine. I have fixed this setting. Thank you for your reminding.

**Comment by Algabri** [comment]
Thanks for your quick reply.
I did as you suggested, but I got the a new issue. It is: 
`FileNotFoundError: [Errno 2] No such file or directory: './HPE/images/validation/2000100001.jpg'`
when I set up l`oad_pkl_flag = False`
It generated them with an empty figure.

**Comment by ly0018-yang** [comment]
I also have this error, how did you solve it？
