### ISSUE TITLE
Where's the pretrained weight of DirectMHP?

### ISSUE THREAD

**Issue by David-19940718** [hnuzhy/DirectMHP#4]
Hi, thank u for your awesome job! Can u provide the pretrained weight, e.g., runs/DirectMHP/agora_m_1280_e300_t40_lw010/weights/best.pt?

**Comment by hnuzhy** [comment]
> Hi, thank u for your awesome job! Can u provide the pretrained weight, e.g., runs/DirectMHP/agora_m_1280_e300_t40_lw010/weights/best.pt?

I have just uploaded the models of DirectMHP-S/M trained on AGORA-HPE. Please refer the updated README.md file.

**Comment by David-19940718** [comment]
> > Hi, thank u for your awesome job! Can u provide the pretrained weight, e.g., runs/DirectMHP/agora_m_1280_e300_t40_lw010/weights/best.pt?
> 
> I have just uploaded the models of DirectMHP-S/M trained on AGORA-HPE. Please refer the updated README.md file.

I really appreciate it! Thank you so much.
