### ISSUE TITLE
Training custom dataset

### ISSUE THREAD

**Issue by David-19940718** [hnuzhy/DirectMHP#6]
Hi, under the disturbance again, now I have a custom task to estimate the posture of the head. If I want to train this model to estimate the three angles (pitch, yam, roll), In order to get label information similar to Agora, which method or label toolkit can I utilize?

**Comment by hnuzhy** [comment]
It is not a trivial task to obtain the head pose ground-truths of 2D images. You should have accurate 3D landmarks + Cam parameters to automatically generate reliable head pose labels like what we have done for constructing AGORA-HPE and CMU-HPE (refer [data_process_hpe.py](https://github.com/hnuzhy/DirectMHP/blob/main/exps/AGORA/data_process_hpe.py) and [data_statistic_hpe.py](https://github.com/hnuzhy/DirectMHP/blob/main/exps/CMU/data_statistic_hpe.py)). Or you may generate rough head pose labels of face-visiable heads by applying off-the-self single HPE models like what methods [img2pose](https://github.com/vitoralbiero/img2pose) and [RetinaFace](https://insightface.ai/retinaface) did. This weakly supervised learning way seems to be a shortcut for realizing engineering applications with low accuracy requirements.

Anyway, how to get the reliable head pose label from a single in-the-wild 2D RGB image is a challenging and ambiguous problem. A rencent similar work [DAD-3DHeads](https://github.com/PinataFarms/DAD-3DHeads) tried to manually annotate 3D head meshs of 2D images. In this way, head pose is an incidental product. I think this is a promising perspective.
